# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget igl::core igl::common)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target igl::core
add_library(igl::core STATIC IMPORTED)

set_target_properties(igl::core PROPERTIES
  INTERFACE_LINK_LIBRARIES "igl::common"
)

# Create imported target igl::common
add_library(igl::common INTERFACE IMPORTED)

set_target_properties(igl::common PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IGL_STATIC_LIBRARY;NOMINMAX"
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_COMPILE_OPTIONS "/MP;/bigobj"
  INTERFACE_INCLUDE_DIRECTORIES "F:/Documents/Visual Studio 2019/projects/libigl/cmake/../include;F:/Documents/Visual Studio 2019/projects/libigl/cmake/../external/eigen"
)

# Import target "igl::core" for configuration "Debug"
set_property(TARGET igl::core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(igl::core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "F:/Documents/Visual Studio 2019/projects/libigl/vs2019/Debug/igl.lib"
  )

# Import target "igl::core" for configuration "Release"
set_property(TARGET igl::core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(igl::core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "F:/Documents/Visual Studio 2019/projects/libigl/vs2019/Release/igl.lib"
  )

# Import target "igl::core" for configuration "RelWithDebInfo"
set_property(TARGET igl::core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(igl::core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "F:/Documents/Visual Studio 2019/projects/libigl/vs2019/RelWithDebInfo/igl.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
